<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.3.7 setup script
 * Date: Wed, 21 Jan 2015 02:04:00 +0100
 */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>